### ISSUE TITLE
 An error has occurred while processing LDS xxxxxx

### ISSUE THREAD

**Issue by hbopuri** [artificialsolutions/inquire_etl#4]
I compiled the new code and ran it. Ended up with this error

> Currently processing config.properties
> Output file path: C:/Server/Jobs/inquire_etl/temp/config.properties/
> Starting processing data from https://xxxxx-inquire.teneocloud.com/teneo-inquire/rest at Tue Feb 28 19:18:08 UTC 2023
> ERROR: **An error has occurred while processing LDS xxxx_bot_jbapp_en_prod_1**. Will continue processing the others, please run this one again.
> <html>
> <head><title>503 Service Temporarily Unavailable</title></head>
> <body>
> <center><h1>503 Service Temporarily Unavailable</h1></center>
> </body>
> </html>

My command is

> java -jar "inquire_etl.jar" --config="config.properties" --azure_sql

**Comment by gurbuuz** [comment]
Hi, this is likely due to an error from the endpoint you were using. If this issue still exists, could you create a forum post here instead; https://community.teneo.ai/ ?

Warm regards,
